version: '3.3'
services:
  postgres-db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOSTNAME
      - DB_PORT
      - POSTGRES_HOST_AUTH_METHOD=trust

  sprocket-api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOSTNAME
      - DB_PORT
      - DJANGO_SETTINGS_MODULE=app.settings
    depends_on:
      - postgres-db

volumes:
  db_data: